#!/bin/sh

for i in good/*.strl; do
    echo 'ADD_TEST(test_comb_'`basename $i .strl` '"./run_test"' '"-k"  "'$i'")'
    echo 'ADD_TEST(test_comb_nodo_'`basename $i .strl` '"./run_test"' '"-kn"  "'$i'")'
    echo 'ADD_TEST(test_comb_return'`basename $i .strl` '"./run_test"' '"-kc"  "'$i'")'
done

for i in bad/*.strl; do
    echo 'ADD_TEST(bad_comb_'`basename $i .strl` '"./run_bad"' '"-k"  "'$i'")'
    echo 'ADD_TEST(bad_comb_nodo_'`basename $i .strl` '"./run_bad"' '"-kn"  "'$i'")'
    echo 'ADD_TEST(bad_comb_return_'`basename $i .strl` '"./run_bad"' '"-kc"  "'$i'")'
done
