#!/bin/sh

COMPILER=../esterml.rml.d.byte
NB_STEPS=10

( $COMPILER -n $NB_STEPS $2 $1 ) & pid=$!
( sleep 1 && kill -HUP $pid >/dev/null 2>/dev/null) & wait $pid

if test $? -eq 2; then exit 0; else exit 1; fi